sudo: false # http://docs.travis-ci.com/user/workers/container-based-infrastructure/
language: node_js
node_js:
  - 0.12

notifications:
  email:
    - medikoo+bespoke-notes@medikoo.com

script: "npm run lint"
